---
- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Stop existing Tomcat if running
  systemd:
    name: tomcat
    state: stopped
  ignore_errors: yes

- name: Remove existing Tomcat
  file:
    path: "{{ tomcat_install_dir }}"
    state: absent

- name: Create Tomcat group
  group:
    name: "{{ tomcat_group }}"

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    shell: /bin/false

- name: Create install directory
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Download Tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes

- name: Set permissions
  file:
    path: "{{ tomcat_install_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Create symlink
  file:
    src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_symlink }}"
    state: link

- name: Deploy systemd service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify:
    - Reload systemd
    - Restart Tomcat
